export const restaurantSummarys = [
    "😊 Good feedback: Customers praise the delicious food, especially the pottery meat, and highlight the exceptional service and atmosphere.\n 😐 Mixed feedback: Some reviewers mention the food being slightly above average in terms of pricing and express disappointment with reheated dishes, portion sizes, and a lackluster atmosphere. \n😞 Bad feedback: A few customers find the food mediocre, noting small portions for the high prices and mentioning issues with the cocktails and authenticity of the Turkish cuisine.",
    "😊 Good feedback: Customers appreciate the diverse menu with options for both vegetarians and non-vegetarians, praising dishes like vegetable couscous and chicken soup, along with attentive service from waiters like Polat and Deniz. \n😐 Mixed feedback: Some reviewers mention higher prices and recommend checking prices carefully, while others have mixed experiences with the food quality. \n😞 Bad feedback: A negative review highlights significantly higher prices for similar dishes compared to other restaurants and mentions issues with food quality, including blood in meatballs and unpleasant chicken.",
    "😊 Good feedback: Customers appreciate the large menu selection, generous portions, delightful service, and the cute ambiance, making it a recommended choice for dining in Istanbul.\n 😐 Mixed feedback: One review mentions higher prices compared to average Turkish restaurants and a simple interior, while another notes a slightly dry salmon dish and slow service. \n😞 Bad feedback: A negative review highlights disappointment with the pricing, a simple street view, and food not being particularly special.",
    "😊 Good feedback: Customers praise the flavorful lentil soup, the Shepherd's Roasted, and the Turkish tea. They appreciate the rich flavors, tender beef, and complimentary baklava. The warm and friendly service, including complimentary dishes, is also highly regarded. \n😐 Mixed feedback: One negative review mentions disappointment in the food, describing it as tasteless and overpriced. The reviewer also questions the authenticity of some of the positive reviews.\n 😞 Bad feedback: Another negative review criticizes the food as completely tasteless and the prices as overly high, despite friendly hosts. The reviewer suspects fake positive reviews to counteract genuine low ratings.",
    "😊 Good feedback: Customers praise the delicious and reasonably priced food. They highlight the welcoming staff and the variety of flavorful dishes, including pasta, stew, kebap, and clay pot. The family-run atmosphere is appreciated, making diners feel at home.\n 😐 Mixed feedback: One review mentions that the restaurant is not particularly Instagramable but offers excellent Turkish cuisine. \n😞 Bad feedback: A negative review mentions that the prices are relatively high for the area, particularly for alcohol. However, the complimentary baklava and tea provided after the meal are seen as a nice touch.",
    "😊 Good feedback: Patrons appreciate the very friendly staff and describe the bar as a nice little place. The extended happy hour with 2-4-1 cocktails and cheap beer is highly praised. It's seen as a great stop along the way.\n 😐 Mixed feedback: One review notes that while they had a positive experience with good customer service, they didn't like one of the drinks they ordered. However, the staff promptly replaced it at no extra charge. Prices are considered reasonable. \n😞 Bad feedback: There is no specific negative feedback mentioned in the available reviews.",
    "😊 Good feedback: Customers rave about the fantastic atmosphere at this Irish pub. They praise the friendly bartender, Leo, who speaks English very well. The creamy Guinness beer is highly regarded, and the pub is seen as a must-visit spot for a pint of Guinness or a Celtic match. \n😐 Mixed feedback: No mixed feedback is mentioned in the available reviews. Customers seem to have had consistently positive experiences. \n😞 Bad feedback: There is no specific negative feedback mentioned in the available reviews.",
    "😊 Good feedback: Customers appreciate the friendly staff, good wine, and reasonably priced beer. The bar is known for its great music selection, sometimes with a live DJ, tasty cocktails, and excellent service from staff members like Yasin and Salih.\n 😐 Mixed feedback: No mixed feedback is mentioned in the available reviews. Customers seem to have had consistently positive experiences. \n😞 Bad feedback: One review mentions a negative experience with service, including a long wait for a Turkish coffee and beer. The food is described as mediocre, and there were issues with bread quality.",
    "😊 Good feedback: Customers enjoy the atmosphere for watching sports matches, friendly and professional service from bartenders like Memet, and the availability of Guinness.\n 😐 Mixed feedback: Some customers find the prices high, especially for items like French fries. There are varying opinions about the quality of food, with some finding it great and others just fair. \n😞 Bad feedback: One reviewer had a negative experience with poor service, slow delivery of food, and high prices, leading them to leave the establishment. Another customer mentions the loud music and high prices, and they feel the pub doesn't match the Irish pub atmosphere.",
    "😊 Good feedback: Customers appreciate the vibrant and charming atmosphere of Just Bar, combining modern cosmopolitan vibes with Turkish culinary traditions. They find the menu offers a variety of options with fair prices, making it an ideal place for a dining experience. The staff, particularly Harun, is friendly and attentive, helping customers have a memorable experience. The cozy and elegant atmosphere is suitable for romantic dinners or fun nights with friends.\n 😐 Mixed feedback: Some customers enjoyed the drinks and hookah, while others found the food quality varying from great to fair. There are mentions of dancing and a DJ, making it a lively spot. \n😞 Bad feedback: A few negative reviews mention high prices and describe a situation where a group felt overcharged. However, the owner responded to one such review, explaining the charges.",
    "😊 Good feedback: Customers praise Old Java Coffee Roasters for its excellent coffee, including lattes, espresso, and filter coffee. The coffee menu includes various plant-based milk options, which is appreciated. Reviewers also highlight the quality of salads and local dishes, describing them as excellent. The atmosphere is described as calm and relaxing, making it an ideal place to start the day.\n 😐 Mixed feedback: Some customers mention that the food, particularly the salad, is a bit acidic, and the bread can be hard to cut. There's also a comment about the price being relatively high for the quantity. \n😞 Bad feedback: A few reviewers found the food not to their liking, describing it as too acidic. They also mentioned high prices in relation to portion sizes. However, these reviews still appreciate the coffee quality and desserts like carrot cake and cookies.",
    "😊 Good feedback: Many customers have praised Coffee No.4 for its fantastic staff who offer friendly and helpful service. The pistachio coffee and lemonade are highly recommended, and the cafe's quiet atmosphere provides a pleasant escape from tourist crowds.\n 😐 Mixed feedback: Some visitors note the presence of tourist crowds, which can affect the overall ambiance, but they still find the coffee and service enjoyable. \n😞 Bad feedback: There are no significant negative comments or complaints about Coffee No.4.",
    "😊 Good feedback: Customers praise the delicious coffee and pleasant atmosphere. The staff is described as polite and friendly, and the coffee is reasonably priced with a wide variety of options.\n 😐 Mixed feedback: Some mixed feedback mentions that the food is standard, with a bit of overpricing. It's seen as a central place with decent coffee. \n😞 Negative reviews mention very long waiting times for food, poor customer service, and overpriced, average-quality food. Some customers were unhappy with the staff's attention and impoliteness.",
    "😊 Good feedback: Customers praise the authentic Turkish coffee experience at Fazil Bey's. The freshly brewed coffee, particularly the Turkish coffee, is highly recommended. The cozy atmosphere and outdoor seating are appreciated.\n 😐 No specific mixed feedback is mentioned in the available reviews. Customers seem to have had consistently positive experiences with the coffee and atmosphere.\n 😞 There is no specific negative feedback mentioned in the available reviews."
];

export function formatAddress(address: `0x${string}`) {
    // Ensure the address is a string and has the expected length
    if (typeof address === 'string' && address.length >= 42) {
      // Get the first 6 characters (including '0x') and the last 4 characters
      return `${address.substring(0, 6)}...${address.substring(address.length - 4)}`;
    }
    return address;
}

